/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-27 00:06:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<title>이달의 룩 - 결제페이지</title>\r\n");
      out.write("		<!-- 파비콘 -->\r\n");
      out.write("		<link rel=\"icon\" href=\"/images/favicon.ico\">\r\n");
      out.write("		 <!-- 글꼴 -->\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <!-- css -->\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/view/payment_non_members_for_window_style.css\"/>\r\n");
      out.write("        \r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("logoDark", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("logoHoverDark", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("mTextColor", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("black", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("menuBtnColor", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("black", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("bgHoverColor", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("#F9F9F9", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("		<h1 class=\"checkout\">Checkout</h1>\r\n");
      out.write("		<hr class=\"line1\"/>\r\n");
      out.write("		<form>\r\n");
      out.write("			<div class=\"user_order_info1\">\r\n");
      out.write("				<h3 >주문정보</h3>\r\n");
      out.write("				<label id=\"title_name\" for=\"name\">이름</label>\r\n");
      out.write("				<input type=\"text\" id=\"name\" name=\"name\"><br/>\r\n");
      out.write("				\r\n");
      out.write("				<label id=\"title_phone_number\" for=\"phone_number\">연락처</label>\r\n");
      out.write("				<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("				<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("				<input type=\"text\" id=\"phone_number\" name=\"phone_number\"><br/>\r\n");
      out.write("				\r\n");
      out.write("				<label id=\"title_email\" for=\"email\">이메일</label>\r\n");
      out.write("				<input type=\"email\" id=\"email\" name=\"email\"><br/>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		<hr class=\"line2\"/>\r\n");
      out.write("		<form>\r\n");
      out.write("			<div class=\"user_order_info2\">\r\n");
      out.write("				<div class=\"shipping-container\">\r\n");
      out.write("					<h3>배송정보</h3>\r\n");
      out.write("  					<div>\r\n");
      out.write("    					<input type=\"checkbox\" id=\"shipping\">\r\n");
      out.write("   						<label for=\"shipping\">주문정보와 동일</label>\r\n");
      out.write("   					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<label id=\"title_name\" for=\"name\">이름</label>\r\n");
      out.write("					<input type=\"text\" id=\"name\" name=\"name\"><br/>\r\n");
      out.write("					\r\n");
      out.write("					<label id=\"title_phone_number\" for=\"phone_number\">연락처</label>\r\n");
      out.write("					<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("					<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("					<input type=\"text\" id=\"phone_number\" name=\"phone_number\"><br/>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"phone_number_additional_box\">\r\n");
      out.write("						<label id=\"title_phone_number_additional\" for=\"phone_number_additional\">추가 연락처</label>\r\n");
      out.write("						<input type=\"text\" id=\"phone_number_additional\" name=\"phone_number_additional\">\r\n");
      out.write("						<input type=\"text\" id=\"phone_number_additional\" name=\"phone_number_additional\">\r\n");
      out.write("						<input type=\"text\" id=\"phone_number_additional\" name=\"phone_number_additional\"><br/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<label id=\"title_address\" for=\"address\">주소</label>\r\n");
      out.write("      				<input type=\"text\" id=\"address_code1\" name=\"address\">\r\n");
      out.write("      				<button id=\"post_button\" type=\"submit\">우편번호 검색</button><br/>\r\n");
      out.write("      				<label id=\"empty_space\" for=\"address\">  </label>\r\n");
      out.write("      				<input type=\"text\" id=\"address_code2\" name=\"address\"><br/>\r\n");
      out.write("      				<label id=\"empty_space\" for=\"address\">  </label>\r\n");
      out.write("      				<input type=\"text\" id=\"remaining_address\" name=\"address\" placeholder=\"나머지 주소 입력\"><br/>\r\n");
      out.write("      				<label id=\"title_shipping_request\" for=\"shipping_request\">배송요청사항</label>\r\n");
      out.write("      				<input type=\"text\" id=\"shipping_request\" name=\"shipping_request\"><br/>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<hr class=\"line3\"/>\r\n");
      out.write("		<form>\r\n");
      out.write("			<div class=\"user_order_info3\">\r\n");
      out.write("				<h3>결제정보</h3>\r\n");
      out.write("				<label id=\"payment_method\" for=\"payment_method\">결제방법</label>\r\n");
      out.write("				\r\n");
      out.write("				<input type=\"checkbox\" id=\"kakaopay\">\r\n");
      out.write("   				<label for=\"kakaopay\">카카오페이(kakaopay)</label><br/>\r\n");
      out.write("   				\r\n");
      out.write("   				<input type=\"checkbox\" id=\"bankbook\">\r\n");
      out.write("   				<label for=\"bankbook\">무통장입금</label><br/>\r\n");
      out.write("				<select id=\"dropdown\" name=\"dropdown\">\r\n");
      out.write("					<option value=\"select\">입금계좌 선택</option>\r\n");
      out.write("					<option value=\"woori_bank\">우리은행 1002-111-222222</option><br/>\r\n");
      out.write("				</select><br/>\r\n");
      out.write("				\r\n");
      out.write("				<input type=\"checkbox\" id=\"credit_card\">\r\n");
      out.write("   				<label for=\"credit_card\">신용카드</label><br/>\r\n");
      out.write("   				\r\n");
      out.write("   				<input type=\"checkbox\" id=\"realtime_bank\">\r\n");
      out.write("   				<label for=\"realtime_bank\">실시간 계좌이체</label><br/>\r\n");
      out.write("   				\r\n");
      out.write("   				<input type=\"checkbox\" id=\"escrow\">\r\n");
      out.write("   				<label for=\"escrow\">에스크로</label><br/>\r\n");
      out.write("   				\r\n");
      out.write("   				<input type=\"checkbox\" id=\"mobile_payment\">\r\n");
      out.write("   				<label for=\"mobile_payment\">휴대폰 결제</label><br/>\r\n");
      out.write("   				\r\n");
      out.write("   				<div id=\"cash_receipts_container\">\r\n");
      out.write("	   				<label id=\"cash_receipts\" for=\"cash_receipts\">현금영수증</label>\r\n");
      out.write("	   				\r\n");
      out.write("	   				<input type=\"checkbox\" id=\"cash_receipts_no\">\r\n");
      out.write("	   				<label for=\"cash_receipts_no\">발급 안 함</label><br/>\r\n");
      out.write("	   				\r\n");
      out.write("	   				<input type=\"checkbox\" id=\"cash_receipts_yes\">\r\n");
      out.write("	   				<label for=\"cash_receipts_yes\">발급</label><br/>\r\n");
      out.write("	   				\r\n");
      out.write("	   				<select id=\"dropdown\" name=\"dropdown\">\r\n");
      out.write("						<option value=\"phone_number\">핸드폰 번호</option>\r\n");
      out.write("						<option value=\"business_number\">사업자 번호</option>\r\n");
      out.write("						<option value=\"revenue\">국세청 현금영수증 카드</option><br/>\r\n");
      out.write("					</select><br/>\r\n");
      out.write("					<div id=\"phone_number_container\">\r\n");
      out.write("						<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("						<input type=\"text\" id=\"phone_number\" name=\"phone_number\">\r\n");
      out.write("						<input type=\"text\" id=\"phone_number\" name=\"phone_number\"><br/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"business_number_container\">\r\n");
      out.write("						<input type=\"text\" id=\"business_number\" name=\"business_number\">\r\n");
      out.write("						<input type=\"text\" id=\"business_number\" name=\"business_number\">\r\n");
      out.write("						<input type=\"text\" id=\"business_number\" name=\"business_number\">\r\n");
      out.write("						<input type=\"text\" id=\"business_number_company_name\" name=\"business_number_company_name\" placeholder=\"업체명\"><br/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"revenue_container\">\r\n");
      out.write("						<input type=\"text\" id=\"revenue_number\" name=\"revenue_number\">\r\n");
      out.write("						<input type=\"text\" id=\"revenue_number\" name=\"revenue_number\">\r\n");
      out.write("						<input type=\"text\" id=\"revenue_number\" name=\"revenue_number\">\r\n");
      out.write("						<input type=\"text\" id=\"revenue_number_last\" name=\"revenue_number_last\"><br/>\r\n");
      out.write("					</div>\r\n");
      out.write("   				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<hr class=\"line4\"/>\r\n");
      out.write("		<form>\r\n");
      out.write("			<div class=\"privacy\">\r\n");
      out.write("				<h3>비회원 구매동의</h3>\r\n");
      out.write("				<h5>개인정보 수집·이용</h5>\r\n");
      out.write("				<table class=\"privacy_table\">\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"33.33%\">\r\n");
      out.write("						<col width=\"33.33%\">\r\n");
      out.write("						<col width=\"33.33%\">	\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"col\">목적</th>\r\n");
      out.write("							<th scope=\"col\">항목</th>\r\n");
      out.write("							<th scope=\"col\">보유기간</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr class=\"privacy1\">\r\n");
      out.write("							<td>주문자 정보 확인, 주문 내역 안내, 주문 내역 조회</td>\r\n");
      out.write("							<td>주문자 정보(이름, 연락처, 이메일)</td>\r\n");
      out.write("							<td id=\"bold\" rowspan=\"4\">주문일로부터 90일까지 보유하며, 관계 법령에 따라<br/> 5년간 보관</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr class=\"privacy2\">\r\n");
      out.write("	                        <td>상품 배송(구매/환불/취소/교환)을 위한 수취인 정보</td>\r\n");
      out.write("	                        <td>수취인 정보(이름, 연락처1, 연락처2, 주소)</td>                     \r\n");
      out.write("                   		</tr>\r\n");
      out.write("                   		<tr class=\"privacy3\" style=\"display: table-row;\">\r\n");
      out.write("	                        <td>무통장 결제 내역 확인을 위한 입금자명</td>\r\n");
      out.write("	                        <td>무통장 입금자명(미입력 시, 주문자명 사용)</td>                   \r\n");
      out.write("                   		</tr>\r\n");
      out.write("                   		<tr class=\"privacy4\" style=\"display: table-row;\">\r\n");
      out.write("	                        <td>현금영수증 발행</td>\r\n");
      out.write("	                        <td>휴대폰번호, 국세청 현금영수증 카드번호</td>                      \r\n");
      out.write("                    	</tr>				\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>					\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<hr class=\"line5\"/>\r\n");
      out.write("		<form>\r\n");
      out.write("			<div class=\"checkout_summary\">\r\n");
      out.write("				<h3>주문요약 및 결제</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"image\">\r\n");
      out.write("						<img src=\"/images/pants.jpg\"> <!-- DB에서 받아오기 -->\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"product_info\">\r\n");
      out.write("						<h4>8036 버뮤다 카펜터 반밴딩 x 1</h4> \r\n");
      out.write("						<div class=\"product-option\">컬러 : 중청, 사이즈 : L</div>\r\n");
      out.write("						<h4 class=\"price\">37,000원</h4>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<hr class=\"line6\"/>\r\n");
      out.write("				<div class=\"pay_summary\">\r\n");
      out.write("					<div class=\"summary_list\">\r\n");
      out.write("						<div class=\"summary_item_subtotal\">\r\n");
      out.write("							<div class=\"label\">주문금액 \r\n");
      out.write("								<span class=\"product_price\" price=\"DB\">37,000원</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						<div class=\"summary_item_shipping\">\r\n");
      out.write("							<div class=\"label\">배송비\r\n");
      out.write("								<span class=\"delivery_price\" price=\"DB\">무료</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"summary_discount\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<div class=\"lable\">할인\r\n");
      out.write("									<span class=\"sale_price\" price=\"DB\">-0원</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"summary_additional\">\r\n");
      out.write("							<div class=\"lable_exception\">추가금액\r\n");
      out.write("								<span class=\"additional_price\" price=\"DB\">0원</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<hr class=\"line7\"/>\r\n");
      out.write("				<div class=\"total_pay_summary\">\r\n");
      out.write("					<div class=\"summary_list2\">\r\n");
      out.write("						<div class=\"summary_total\">\r\n");
      out.write("							<div class=\"lable\">총 결제금액\r\n");
      out.write("								<span class=\"total_price\" price=\"DB\">37000원</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"last_checkout\">\r\n");
      out.write("					<div class=\"checkout-agreement\">\r\n");
      out.write("                    	<label><input type=\"checkbox\" id=\"pay_agree\" name=\"pay_agree\" form=\"order_form\" class=\"agree_terms\" onclick=\"javascript_method()\"> 모든 주문, 결제정보를 확인하였으며 진행에 동의합니다.</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"payment_button\"><a href=\"javascript:send();\" class=\"button primary\">결제하기</a></button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</body>		\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
